import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import connectToDatabase from "@/utils/mongodb";
import User from "@/models/User";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  connectToDatabase()
    .then(() => console.log(' MongoDB connection established'))
    .catch((err) => console.error(' MongoDB connection failed:', err));

    console.log(' User model loaded successfully:', !!User);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}